name: Deno CI/CD

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Deps
        run: deno install

      - name: Deno Check
        run: deno check .

      - name: Deno Format Check
        run: deno fmt --check

      - name: Deno Lint
        run: deno lint
