name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.name }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: linux-x86_64
            runner: ubuntu-latest
          - name: windows-x86_64
            runner: windows-latest
          - name: linux-aarch64
            runner: ubuntu-22.04-ARM64

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Deps
        run: deno task install

      - name: Compile
        run: deno task compile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.name }}
          path: dist/

  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    needs: build
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Read version from deno.json
        id: get_version
        run: |
          version=$(jq -r .version deno.json)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Check if tag already exists
        run: |
          if git rev-parse "v${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag already exists"
            exit 1
          fi

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "v${{ steps.get_version.outputs.version }}"
          git push origin "v${{ steps.get_version.outputs.version }}"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.tag.outputs.version }}
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
